//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDATextTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HDATextTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1B=A
        ///1C=B
        ///1D=C
        ///1E=D
        ///1F=E
        ///20=F
        ///21=G
        ///22=H
        ///23=I
        ///24=J
        ///25=K
        ///26=L
        ///27=M
        ///28=N
        ///29=O
        ///2A=P
        ///2B=Q
        ///2C=R
        ///2D=S
        ///2E=T
        ///2F=U
        ///30=V
        ///31=W
        ///32=X
        ///33=Y
        ///34=Z
        ///35=a
        ///36=b
        ///37=c
        ///38=d
        ///39=e
        ///3A=f
        ///3B=g
        ///3C=h
        ///3D=i
        ///3E=j
        ///3F=k
        ///40=l
        ///41=m
        ///42=n
        ///43=o
        ///44=p
        ///45=q
        ///46=r
        ///47=s
        ///48=t
        ///49=u
        ///4A=v
        ///4B=w
        ///4C=x
        ///4D=y
        ///4E=z.
        /// </summary>
        internal static string CharacterTable {
            get {
                return ResourceManager.GetString("CharacterTable", resourceCulture);
            }
        }
    }
}
